### ISSUE TITLE
i will love to do copywriting for you 

### ISSUE THREAD

**Issue by hamzeyto** [Beesham/WeatherApp-Kotlin#1]
I love your application and would want to contribute to it, I'm not a developer but I am good at copywriting. I would love to make a copywrite for your Readme and make a pull request for you to merge. Your response would be highly appreciated. Also I would like to request if we could communicate via email, so I don't have to create issues. Thank you.

**Comment by Beesham** [comment]
The application doesnt need a copyright. It's just  a clone im working
through by following a book (Kotlin For Android Developers by Antonio
Leiva). You are welcome to create a more verbose Readme if you so wish.
